spring.application.name=BlogApplication

server.port=9090

#Databse configuration properties
spring.datasource.url=jdbc:mysql://localhost:3306/blogapp
spring.datasource.username=sooraj
spring.datasource.password=sooraj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true